#!/bin/bash

trap "exit 130" SIGINT
trap "exit 137" SIGKILL
trap "exit 143" SIGTERM

if [[ ${DEBUG} == "true" ]]
then
  set -o xtrace
  DBG="-d"
fi

if [[ ${CHN_FEED_ENABLED} == "true" ]]
then
  mkdir -p /var/www/feeds
  cd /var/www
  exec python3 /opt/chn_feed_generator.py -s ${SLEEP:-60} -r ${DBG}
else
  echo "CHN_FEED_ENABLED not \"true\". Disabling CIF feed generation."
  sleep 300
  exit 0
fi
