#!/bin/bash

trap "exit 130" SIGINT
trap "exit 137" SIGKILL
trap "exit 143" SIGTERM

if [[ ${DEBUG} == "true" ]]
then
  set -o xtrace
  DBG="-d"
fi

if [[ ${CIF_SAFELIST_ENABLED} == "true" ]]
then
  mkdir -p /var/www/safelists
  cd /var/www/safelists
  exec python3 /opt/cif_feed_safelister.py -s ${SAFELIST_SLEEP:-60} -r ${DBG}
else
  echo "CIF_SAFELIST_ENABLED not \"true\". Disabling CIF safelist upload."
  sleep 300
  exit 0
fi
